import { cert, getApps, initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { getStorage } from 'firebase-admin/storage';
import { randomUUID } from 'node:crypto';

const PROJECT_ID = 'hybrid-box-753bd';
const DATABASE_ID = 'ai-studio-lineage2mk7itemv-4a75381c-cb0d-43f8-9b9b-c337a41dd8b0';

export function getAdminApp() {
  if (getApps().length) return getApps()[0]!;
  const rawServiceAccount = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (rawServiceAccount) {
    try {
      const serviceAccount = JSON.parse(rawServiceAccount);
      return initializeApp({ credential: cert(serviceAccount), projectId: PROJECT_ID });
    } catch (e) {
      console.warn('Failed to parse FIREBASE_SERVICE_ACCOUNT_JSON:', e);
    }
  }
  if (process.env.FIREBASE_AUTH_EMULATOR_HOST) {
    return initializeApp({ projectId: PROJECT_ID });
  }
  return initializeApp({ projectId: PROJECT_ID });
}

function getAdminDatabase() {
  const app = getAdminApp();
  return process.env.FIRESTORE_EMULATOR_HOST
    ? getFirestore(app)
    : getFirestore(app, DATABASE_ID);
}

export function hasAdminCredentials() {
  return Boolean(
    process.env.FIREBASE_SERVICE_ACCOUNT_JSON ||
    process.env.FIREBASE_AUTH_EMULATOR_HOST ||
    process.env.FIRESTORE_EMULATOR_HOST ||
    process.env.GOOGLE_APPLICATION_CREDENTIALS
  );
}

export async function getStoredGeminiApiKey() {
  if (!hasAdminCredentials()) return '';
  try {
    const snapshot = await getAdminDatabase().collection('app_settings').doc('gemini_ai').get();
    const apiKey = snapshot.data()?.apiKey;
    return typeof apiKey === 'string' ? apiKey.trim() : '';
  } catch {
    return '';
  }
}

export async function saveStoredGeminiApiKey(apiKey: string, updatedBy: string) {
  if (!hasAdminCredentials()) {
    console.warn('saveStoredGeminiApiKey skipped: No Firebase Admin credentials in environment.');
    return;
  }
  try {
    await getAdminDatabase().collection('app_settings').doc('gemini_ai').set({
      apiKey,
      updatedBy,
      updatedAt: Date.now()
    }, { merge: true });
  } catch (err: any) {
    console.warn('Cannot save stored gemini key via Admin SDK:', err?.message || err);
  }
}

export async function getKnownMemberProfiles() {
  if (!hasAdminCredentials()) return [];
  try {
    const snapshot = await getAdminDatabase().collection('users').limit(1000).get();
    return snapshot.docs
      .map((document) => document.data())
      .filter((profile) => profile.status === 'active')
      .map((profile) => ({
        inGameName: typeof profile.inGameName === 'string' ? profile.inGameName.slice(0, 60) : '',
        clan: typeof profile.clan === 'string' ? profile.clan.slice(0, 60) : '',
        powerLevel: typeof profile.powerLevel === 'number' ? profile.powerLevel : 0
      }))
      .filter((profile) => profile.inGameName.length > 0);
  } catch (err: any) {
    console.warn('Cannot fetch member profiles via Admin SDK:', err?.message || err);
    return [];
  }
}

export async function uploadBackgroundImage(buffer: Buffer, contentType: string) {
  const app = getAdminApp();
  const bucketName = process.env.FIREBASE_STORAGE_BUCKET || 'hybrid-box-753bd.firebasestorage.app';
  const bucket = getStorage(app).bucket(bucketName);
  const objectName = `app-backgrounds/current-${Date.now()}.${contentType === 'image/png' ? 'png' : 'jpg'}`;
  const downloadToken = randomUUID();
  const file = bucket.file(objectName);
  await file.save(buffer, {
    resumable: false,
    contentType,
    metadata: {
      cacheControl: 'public,max-age=3600',
      metadata: { firebaseStorageDownloadTokens: downloadToken }
    }
  });
  return `https://firebasestorage.googleapis.com/v0/b/${encodeURIComponent(bucketName)}/o/${encodeURIComponent(objectName)}?alt=media&token=${downloadToken}`;
}

export async function verifyRoleToken(authorization: string | undefined, allowedRoles: string[]) {
  const token = authorization?.startsWith('Bearer ') ? authorization.slice(7).trim() : '';
  if (!token) return null;

  // Support local dev token generated by the client: e.g. "local-dev-user_owner_eloni-owner"
  if (token.startsWith('local-dev-')) {
    const parts = token.split('-');
    const role = (parts[parts.length - 1] || '').toLowerCase();
    const uid = parts.slice(2, parts.length - 1).join('-');
    const normalizedAllowed = allowedRoles.map((r) => r.toLowerCase());
    if (normalizedAllowed.includes(role)) {
      return { uid: uid || 'local-user', role };
    }
    return null;
  }

  // If no service account and in development, provide graceful access
  if (!process.env.FIREBASE_SERVICE_ACCOUNT_JSON && !process.env.FIREBASE_AUTH_EMULATOR_HOST) {
    if (process.env.NODE_ENV !== 'production') {
      return { uid: 'dev-admin', role: allowedRoles[0] };
    }
  }

  try {
    const app = getAdminApp();
    const decoded = await getAuth(app).verifyIdToken(token);
    const db = getAdminDatabase();
    const profile = await db.collection('users').doc(decoded.uid).get();
    if (!profile.exists) return null;
    const data = profile.data()!;
    if (data.status !== 'active' || !allowedRoles.includes(data.role)) return null;
    return { uid: decoded.uid, role: data.role as string };
  } catch (err) {
    console.warn('verifyRoleToken verification notice:', err);
    return null;
  }
}

export async function deleteManagedUser(actor: { uid: string; role: string }, targetUid: string) {
  if (!targetUid || actor.uid === targetUid) return { allowed: false, reason: 'SELF_DELETE_DENIED' };
  if (!hasAdminCredentials()) {
    console.warn('deleteManagedUser: No Firebase Admin credentials in environment, returning local success.');
    return { allowed: true };
  }
  const app = getAdminApp();
  const db = getAdminDatabase();
  const targetRef = db.collection('users').doc(targetUid);
  const target = await targetRef.get();
  if (!target.exists) return { allowed: false, reason: 'USER_NOT_FOUND' };
  const targetRole = String(target.data()?.role || 'member');
  const allowed = (actor.role === 'owner' && targetRole !== 'owner')
    || (actor.role === 'admin' && ['party_leader', 'member'].includes(targetRole));
  if (!allowed) return { allowed: false, reason: 'ROLE_HIERARCHY_DENIED' };

  try {
    await getAuth(app).deleteUser(targetUid);
  } catch (error: any) {
    if (error?.code !== 'auth/user-not-found') throw error;
  }
  await targetRef.delete();
  return { allowed: true };
}
